---
- name: stop ufw
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false

- name: update cache
  apt:
    update_cache=yes cache_valid_time=3600

- name: install traceroute
  ansible.builtin.apt:
    pkg:
    - traceroute

- name: install iptables-persistent
  ansible.builtin.apt:
    pkg:
    - iptables-persistent
  when: (ansible_hostname == "inetRouter")

- name: enable iptables-persistent
  ansible.builtin.service:
    name: iptables.service
    enabled: true
  when: (ansible_hostname == "inetRouter")

- name: Set up NAT on inetRouter
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: "iptables_rules.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0640" }
  when: (ansible_hostname == "inetRouter")

- name: apply iptables rules
  ansible.builtin.shell: /sbin/iptables-restore < /etc/iptables_rules.ipv4
  when: (ansible_hostname == "inetRouter")

- name: safe iptables rules
  ansible.builtin.shell: netfilter-persistent save
  when: (ansible_hostname == "inetRouter")

- name: set up forward packages across routers
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    state: present
  when: "'routers' in group_names"

- name: disable default route
  template:
    src: 50-cloud-init.yaml
    dest: /etc/netplan/00-installer-config.yaml
    owner: root
    group: root
    mode: 0600
  when: (ansible_hostname != "inetRouter")

- name: netplan try
  ansible.builtin.shell: netplan try

- name: add default gateway for centralRouter
  template:
    src: "50-vagrant_{{ansible_hostname}}.yaml"
    dest: /etc/netplan/50-vagrant.yaml
    owner: root
    group: root
    mode: 0600

- name: restart all hosts
  reboot:
    reboot_timeout: 600
